on:
  push:
  schedule:
    - cron: "0 3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          cache: pip
          python-version: '3.13'
      - run: pip install -r requirements.txt
      - run: python daily.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          WEATHERAPI_KEY: ${{ secrets.WEATHERAPI_KEY }}

