on:
  push:
  schedule:
    - cron: "10 9 * * *"

permissions:
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: America/Vancouver
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          cache: pip
          python-version: '3.13'
      - run: sudo apt-get install ffmpeg -y
      - run: pip install -r requirements.txt
      - run: python daily.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          WEATHERAPI_KEY: ${{ secrets.WEATHERAPI_KEY }}
          EVENTS_URL: ${{ vars.EVENTS_URL }}
      - run: python publish.py
      - name: Setup page contents
        run: mkdir -p page && mv index.html feed.xml *.mp3 *.aac page
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Save output
        uses: actions/upload-pages-artifact@v3
        with:
          path: page
      - name: Deploy to pages
        uses: actions/deploy-pages@v4
      - run: python schedule.py
        env:
          AZURA_API_BASE: https://platform.haidagwaiiradio.org/api
          AZURA_STATION_ID: shedfm
          PLAYLIST_ID: 16
          AZURA_API_KEY: ${{ secrets.AZURA_API_KEY }}
